apiVersion: v1
kind: PersistentVolume
metadata:
  name: pneumodetect-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/pneumodetect-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pneumodetect-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
